const governorates = [
    { apiName: "Cairo", displayName: "القاهرة" },
    { apiName: "Giza", displayName: "الجيزة" },
    { apiName: "Alexandria", displayName: "الإسكندرية" },
    { apiName: "Qalyubia", displayName: "القليوبية" },
    { apiName: "El Dakahlia", displayName: "الدقهلية" },
    { apiName: "Sharqia", displayName: "الشرقية" },
    { apiName: "Gharbia", displayName: "الغربية" },
    { apiName: "El Monufia", displayName: "المنوفية" },
    { apiName: "Beheira", displayName: "البحيرة" },
    { apiName: "Kafr El-Sheikh", displayName: "كفر الشيخ" },
    { apiName: "Damietta", displayName: "دمياط" },
    { apiName: "Port Said", displayName: "بورسعيد" },
    { apiName: "Suez", displayName: "السويس" },
    { apiName: "Ismailia", displayName: "الإسماعيلية" },
    { apiName: "North Sinai", displayName: "شمال سيناء" },
    { apiName: "South Sinai", displayName: "جنوب سيناء" },
    { apiName: "Beni Suef", displayName: "بني سويف" },
    { apiName: "Fayoum", displayName: "الفيوم" },
    { apiName: "Minya", displayName: "المنيا" },
    { apiName: "Assiut", displayName: "أسيوط" },
    { apiName: "Sohag", displayName: "سوهاج" },
    { apiName: "Qena", displayName: "قنا" },
    { apiName: "Luxor", displayName: "الأقصر" },
    { apiName: "Aswan", displayName: "أسوان" },
    { apiName: "Hurghada", displayName: "الغردقة" },
    { apiName: "New Valley", displayName: "الوادي الجديد" },
    { apiName: "Matrouh", displayName: "مطروح" },
  ];
  
  export default governorates;  